[project]
name = "nts-now"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.7",
    "pytz>=2024.2",
    "requests>=2.32.3",
    "rich>=13.9.4",
]
